### ISSUE TITLE
KeyError: "sequence '1' not present"

### ISSUE THREAD

**Issue by husamia** [kcleal/dysgu#11]
I am running dysgu installed on Linux WSL2 (Windows 10). The command is default

`dysgu run -p4 GRCh38_full_analysis_set_plus_decoy_hla.fa sample.bam > sample_dysgu_sv.vcf
`

the data is 30x WGS (illumina) PE 150. The output an empty vcf, the folder contains 25 bin files and the reads.bam file which is about 30GB. The output log is too long to paste but here is the last few lines of it.

```
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/husamia/.local/lib/python3.8/site-packages/dysgu/main.py", line 220, in run_pipeline
    cluster.cluster_reads(ctx.obj)
  File "/home/husamia/.local/lib/python3.8/site-packages/dysgu/re_map.py", line 473, in drop_svs_near_reference_gaps
    logging.warning("Error fetching reference chromosome: {}".format(chrom), errors)
Message: 'Error fetching reference chromosome: Y'
Arguments: (KeyError("sequence 'Y' not present"),)
2021-07-13 15:33:00,848 [INFO   ]  N near gaps dropped 0

2021-07-13 15:33:45,354 [INFO   ]  Loaded n=25 chromosome coverage arrays from /mnt/e/20A0012672_Proband/dysgu
2021-07-13 15:35:37,356 [INFO   ]  Adding genotype
Traceback (most recent call last):
  File "/home/husamia/.local/bin/dysgu", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/husamia/.local/lib/python3.8/site-packages/dysgu/main.py", line 220, in run_pipeline
    cluster.cluster_reads(ctx.obj)
  File "dysgu/cluster.pyx", line 1051, in dysgu.cluster.cluster_reads
  File "dysgu/cluster.pyx", line 970, in dysgu.cluster.pipe1
  File "dysgu/post_call_metrics.pyx", line 465, in dysgu.post_call_metrics.ref_repetitiveness
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence '1' not present"
```

**Comment by husamia** [comment]
I was using the wrong reference. Closed
