### ISSUE TITLE
Problem in re genotyping a sample using merged sites

### ISSUE THREAD

**Issue by edg1983** [kcleal/dysgu#15]
Hi,

Nice tool! I like that it can run with both short and long reads.
In my case I have few small families (duos or trios) sequenced using PacBio HiFi reads for which I want to create family VCFs

Following your suggestions I've first generated SV calls for each individual using `dysgu run --mode pacbio`, then for each family I've merged calls from the various family members using `dysgu merge vcf_sample1.vcf vcf_sample2.vcf | bgzip -c > merged.vcf.gz`

Finally I want to re-call SV so I've tried something like the following
```
dysgu run -p12 --mode pacbio --sites merged.vcf.gz --sites-prob 0.8 --all-sites True GRCh38.fa tmpdir sample1.bam
```
I've tried the above also using uncompressed merged file and without `--site-prob` and the results are the same as described below

In the beginning, the tool seems to run fine and it can read variants from my input I think. Here is an extract of the log:
```
2021-11-16 15:35:56,906 [INFO   ]  Writing vcf to stdout
2021-11-16 15:35:56,906 [INFO   ]  Running pipeline
2021-11-16 15:35:56,940 [INFO   ]  Minimum support 2
2021-11-16 15:35:56,940 [INFO   ]  Reading --sites
2021-11-16 15:35:57,623 [INFO   ]  Building graph with clustering 500000 bp
2021-11-16 15:36:31,347 [INFO   ]  Total input reads 244912
2021-11-16 15:36:31,417 [INFO   ]  Added 43336 variants from input sites
2021-11-16 15:36:31,504 [INFO   ]  Graph constructed
```

But then just after that I always get this error:
```
Traceback (most recent call last):
  File "/well/gel/HICF2/software/conda_envs/dysgu/bin/dysgu", line 8, in <module>
    sys.exit(cli())
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/site-packages/dysgu/main.py", line 280, in run_pipeline 
    cluster.cluster_reads(ctx.obj)
  File "dysgu/cluster.pyx", line 1115, in dysgu.cluster.cluster_reads
  File "dysgu/cluster.pyx", line 919, in dysgu.cluster.pipe1
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/gpfs3/well/gel/HICF2/software/conda_envs/dysgu/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'dysgu.sites_utils.Site'>: attribute lookup Site on dysgu.sites_utils failed
```

Any idea of possible solutions?

Thanks!

**Comment by kcleal** [comment]
Hi Edoardo,

Thanks for reporting this. I will try and address this for you, although I am a little confused as to the reason at the moment. Would you be able to try running using `-p1`? It appears to be a result of pickling that is only used in multiprocessing. Thanks

**Comment by kcleal** [comment]
I found the issue - it was a problem of defining a namedTuple type in a local scope. The problem can be avoided by using `-p1`
I have uploaded a fix for the issue to github. However, I have a few more updates to add before I push the release to pypi for installing via `pip`. So I recommend running with `-p1` for now. Thanks!

**Comment by edg1983** [comment]
Hi Thanks for the solution! Running with `-p1` worked fine and generated VCF output.

However, there is this error reported several times during the process
```
ValueError: Graph contains a cycle.
Exception ignored in: 'dysgu.assembler.topo_sort2'
```

Is it something to care about or is something related to PacBio HiFi reads? (I didn't see this when running on Illumina paired-end data)

**Comment by kcleal** [comment]
Glad to hear it. Thanks for raising this further error too. I have not seen this error before, but will probably result in a failure of contig generation for the SV event, which might then lead to a lower probability score from the model. I suspect it might occur on non-canonical reference chromosome, or possibly at chromosome gaps/ends. Could I ask what is the read coverage you are using, and roughly how many times this error is reported on your run? 

I think it will be tricky to debug without a better error report, so in the next release I will make sure a more helpful error message is reported. Thanks again!
