### ISSUE TITLE
Error with --max-cov auto

### ISSUE THREAD

**Issue by jdemeul** [kcleal/dysgu#32]
Hi @kcleal and thanks for the great tool!

I was playing around with a few settings and ran into the following error when trying out `--max-cov auto`.
Note that the pipeline runs perfectly when this is set to -1 or the default 200 for instance.

```
2022-03-23 19:26:25,545 [INFO   ]  [dysgu-run] Version: 1.3.7
2022-03-23 19:26:25,546 [INFO   ]  run --mode nanopore --diploid True --min-support 3 --min-size 30 --max-cov auto -o output.vcf -p 18 -c genome.fa /scratch input.bam
2022-03-23 19:26:25,546 [INFO   ]  Destination: /scratch
[W::hts_idx_load3] The index file is older than the data file: input.bam.bai
Traceback (most recent call last):
  File "/opt/venv/bin/dysgu", line 8, in <module>
    sys.exit(cli())
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/dysgu/main.py", line 270, in run_pipeline
    max_cov_value = sv2bam.process(ctx.obj)
  File "dysgu/sv2bam.pyx", line 165, in dysgu.sv2bam.process
  File "dysgu/coverage.pyx", line 47, in dysgu.coverage.auto_max_cov
TypeError: 'bool' object is not callable
```

**Comment by kcleal** [comment]
Hi @jdemeul,
Thanks for reporting this. I have fixed the bug, but you will have to dysgu build from source until I release a patch to pypi for instaling via `pip install dysgu`. In the mean time, you can try the `suggest_max_coverage.py` script found in the `scripts` folder which achieves the same result:

`max_cov=$(python $DYSGU_PATH/scripts/suggest_max_coverage.py input.bam)`
`dysgu run --mode nanopore --diploid True --min-support 3 --min-size 30 --max-cov $max_cov -o output.vcf -p 18 -c genome.fa /scratch input.bam`

**Comment by jdemeul** [comment]
Awesome, thanks a lot for the quick fix and workaround @kcleal !
