### ISSUE TITLE
SV calling NOT working

### ISSUE THREAD

**Issue by sachingadakh** [kcleal/dysgu#43]
Hello,
 I have used dysgu for SV calling earlier without facing any errors but suddenly now I facing following error. Can you please help me what's going wrong, since google didn't show any possible solution

command : dysgu call --mode nanopore -p 20 ../../hg38.fa work_dir/ --ibam HG00733.sortedmappeddedup.bam > HG00733_ONTlee_dysgu.vcf

error : 
2022-07-11 12:11:04,948 [INFO   ]  [dysgu-call] Version: 1.3.11
Traceback (most recent call last):
  File "/home/sachin/miniconda3/bin/dysgu", line 8, in <module>
    sys.exit(cli())
  File "/home/sachin/miniconda3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sachin/miniconda3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sachin/miniconda3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sachin/miniconda3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sachin/miniconda3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sachin/miniconda3/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sachin/miniconda3/lib/python3.8/site-packages/dysgu/main.py", line 431, in call_events
    raise ValueError("Could not find '{}'".format(kwargs["sv_aligns"]))
ValueError: Could not find 'None'

**Comment by kcleal** [comment]
Hi @sachingadakh,
I believe you are missing an argument in your command. The `--ibam` option is only used for calculating insert-size's (paired-end data only) and is not used for the SV calling. I think the command you are after is:

`dysgu call --mode nanopore -p 20 ../../hg38.fa work_dir HG00733.sortedmappeddedup.bam > HG00733_ONTlee_dysgu.vcf`

**Comment by sachingadakh** [comment]
Hello,
  Yes, I agree with you, since I have been using several SV callers at a time and getting confused with the working directory parameter, dysgu creates the working directory by itself provided with just a label, not the pre-created working/temp directory created like other SV callers. I believe previously when I used dysgu to call SV was the right way and in agreement with the command, you suggested where work_dir is to be created by the SV caller itself but not the pre-created directory provided by the user.
 Thank you for the response to such a small issue but it has really helped me to clear confusion and stalled work.
