### ISSUE TITLE
Invalid character '.' in 'GQ' FORMAT field

### ISSUE THREAD

**Issue by arunvv90** [kcleal/dysgu#45]
Hi,
I got a problem with dysgu merging multiple samples and genotyping. I have twenty samples. First, SVs were called on each of them and merged. However, genotyping with the merged vcf file has failed with the following error.
ATCC BCAHV C02-169 C96-152 C97-256 C98-172 LA87-305 LA90-390 S03-468 S09-363 S09-391 S09-398 S11-140 S11-366 S11-375 S11-462 S11-467 S98-108 S98-595 S99-1170
20
Dysgu is Processing  ATCC
2022-07-24 09:03:54,699 [INFO   ]  [dysgu-call] Version: 1.3.11
2022-07-24 09:03:54,700 [INFO   ]  Input file is: /ssd2/av724/var_jul19/final2/minimap2_snf/ATCC.bam
2022-07-24 09:03:54,700 [INFO   ]  call --sites /ssd2/av724/var_jul19/final2/dysgu_np30x/ver2/dy_poplnmerg.vcf /ssd2/av724/varanalysis/reference/atcc_ref_ccv.fna /ssd2/av724/var_jul19/final2/dysgu_np30x/ver2/ATCC-temp /ssd2/av724/var_jul19/final2/minimap2_snf/ATCC.bam
2022-07-24 09:03:54,700 [WARNING]  Warning: no @RG, using input file name as sample name for output: ATCC
2022-07-24 09:03:54,700 [INFO   ]  Sample name: ATCC
2022-07-24 09:03:54,700 [INFO   ]  Writing vcf to stdout
2022-07-24 09:03:54,700 [INFO   ]  Running pipeline
2022-07-24 09:03:54,764 [INFO   ]  Inferred read length 3398.0
2022-07-24 09:03:54,764 [INFO   ]  Max clustering dist 1050
2022-07-24 09:03:54,764 [INFO   ]  Minimum support 3
2022-07-24 09:03:54,764 [INFO   ]  Reading --sites
[E::vcf_parse_format] Invalid character '.' in 'GQ' FORMAT field at NC_001493.2:78
Traceback (most recent call last):
  File "/home/av724/miniconda3/envs/dysgu2/bin/dysgu", line 8, in <module>
    sys.exit(cli())
  File "/home/av724/miniconda3/envs/dysgu2/lib/python3.7/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/home/av724/miniconda3/envs/dysgu2/lib/python3.7/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/home/av724/miniconda3/envs/dysgu2/lib/python3.7/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/av724/miniconda3/envs/dysgu2/lib/python3.7/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/av724/miniconda3/envs/dysgu2/lib/python3.7/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/home/av724/miniconda3/envs/dysgu2/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/av724/miniconda3/envs/dysgu2/lib/python3.7/site-packages/dysgu/main.py", line 444, in call_events
    cluster.cluster_reads(ctx.obj)
  File "dysgu/cluster.pyx", line 1337, in dysgu.cluster.cluster_reads
  File "dysgu/cluster.pyx", line 917, in dysgu.cluster.pipe1
  File "/home/av724/miniconda3/envs/dysgu2/lib/python3.7/site-packages/dysgu/sites_utils.py", line 61, in vcf_reader
    for idx, r in enumerate(vcf):
  File "pysam/libcbcf.pyx", line 4175, in pysam.libcbcf.VariantFile.__next__

I checked the VCF file. Here in the field at NC_001493.2:78, GQ is equal to MAPQ. In the header file, GQ is defined as an integer and MAPQ is a Float. This is causing the problem. I changed the GQ datatype from integer to float. It solved the problem. I hope this will not affect the results. Please let me know your suggestion.

**Comment by kcleal** [comment]
Hi @arunvv90, thanks for reporting this. I will get this fixed. Could I ask, what's version of dysgu are you using?

**Comment by arunvv90** [comment]
I am using dysgu, version 1.3.11

**Comment by kcleal** [comment]
Is the GC field listed as ".", or do you mean it is listed as a floating point number? E.g. "21.1"

**Comment by arunvv90** [comment]
I think I confused you. Error is indicating that '.' is in the GQ column.
Then I checked the data type. It is an integer, not a Float. I change this
in line 44 of VCF file. I am attaching the modified file. If you change the
Float back to integer then I guess you can reproduce the issue.

*Arun Venugopalan*
Ph.D Scholar
Infectious Diseases, Basic Science Dept.
College of Veterinary Medicine
Mississippi State University*,* USA

**Comment by kcleal** [comment]
This has been fixed in v1.3.12
