### ISSUE TITLE
About Pacio ccs.bam

### ISSUE THREAD

**Issue by ClarenceHsiang** [kcleal/dysgu#52]
Dear dysgu team,

Good afternoon.

I used ccs.bam file as input in dysqu program as below,

dysgu call --mode pacbio NK.fasta pb.large.ccs.bam > PbNK.vcf

However, I got the Error like this:

"Traceback (most recent call last):
  File "/home/hsiang/miniconda3/envs/Python3_9/bin/dysgu", line 5, in <module>
    from dysgu.main import cli
  File "/home/hsiang/miniconda3/envs/Python3_9/lib/python3.9/site-packages/dysgu/__init__.py", line 2, in <module>
    from dysgu.python_api import DysguSV,\
  File "/home/hsiang/miniconda3/envs/Python3_9/lib/python3.9/site-packages/dysgu/python_api.py", line 9, in <module>
    from dysgu.cluster import pipe1, merge_events
  File "dysgu/cluster.pyx", line 1, in init dysgu.cluster
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject"

Should I run pbmm2 align to get the new alignment bam?

Thank you very much

Sincerely yours,

Clarence

**Comment by kcleal** [comment]
Hi @ClarenceHsiang, this looks like a problem with the install. I can recommend either re installing numpy, building dysgu from source, or possibly try python3.10 if you have that available.
