### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by xiekunwhy** [kcleal/dysgu#54]
Hi,

Would you please add dysgu to bioconda.

After trying very hard to install dysgu, I got following errors, do you know why?
dysgu -h
Traceback (most recent call last):
  File "/Bio/User/kxie/software/anaconda3/envs/dysgu/bin/dysgu", line 5, in <module>
    from dysgu.main import cli
  File "/Bio/User/kxie/software/anaconda3/envs/dysgu/lib/python3.9/site-packages/dysgu/main.py", line 11, in <module>
    from dysgu import cluster, view, sv2bam
  File "dysgu/cluster.pyx", line 15, in init dysgu.cluster
  File "dysgu/coverage.pyx", line 5, in init dysgu.coverage
  File "dysgu/io_funcs.pyx", line 19, in init dysgu.io_funcs
  File "/Bio/User/kxie/software/anaconda3/envs/dysgu/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

Best,
Kun

**Comment by kcleal** [comment]
Hi @xiekunwhy,
Hopefully this error was fixed in the latest release a few days ago v1.3.14 https://github.com/kcleal/dysgu/commit/13eceea35f799825afa96b4839a287a1ab4fb908. If you have an earlier version of dysgu, it can be resolved by switching to numpy <= v1.21.
I will try and get dysgu added to bioconda

**Comment by kcleal** [comment]
FYI, dysgu can now be installed with `conda install -c bioconda -c conda-forge dysgu`
