### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject

### ISSUE THREAD

**Issue by zengxi-hada** [kcleal/dysgu#60]
Hi,

May I ask how to resolve the issue below?
**dysgu run -p4 /n/data1/bch/genetics/lee/reference/b37/human_g1k_v37_decoy.fasta temp_dir /n/scratch3/users/x/xiz978/L1_mediated_SV/data/HG002_Genome_in_the_Bottle/HG002_hs37d5_ONT-UL_GIAB_20200122.phased.bam > HG002_ONT.vcf**

Traceback (most recent call last):
  File "/home/xiz978/anaconda3/bin/dysgu", line 5, in <module>
    from dysgu.main import cli
  File "/home/xiz978/anaconda3/lib/python3.9/site-packages/dysgu/__init__.py", line 2, in <module>
    from dysgu.python_api import DysguSV,\
  File "/home/xiz978/anaconda3/lib/python3.9/site-packages/dysgu/python_api.py", line 9, in <module>
    from dysgu.cluster import pipe1, merge_events
  File "dysgu/cluster.pyx", line 1, in init dysgu.cluster
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject

**Comment by kcleal** [comment]
Hi @zengxi-hada,
I have come across this error before, I do not know what causes it though. I think I managed to resolve it by just re-installing numpy and dysgu. How did you install dysgu this time?

**Comment by zengxi-hada** [comment]
Hi,

I just installed it using "pip install numpy dysgu".
Thank you!

**Comment by kcleal** [comment]
You might need to run ```pip uninstall numpy``` a few times to remove other versions. Alternatively, the conda install route should work

**Comment by zengxi-hada** [comment]
> You might need to run `pip uninstall numpy` a few times to remove other versions. Alternatively, the conda install route should work

I have tried your method. But it still cannot work. Thank you all the same.

**Comment by kcleal** [comment]
Hi @zengxi-hada, did you manage to install dysgu? Come to think of it, you could also try reinstalling pysam. Or if you have conda available, try creating a conda environment...

**Comment by zengxi-hada** [comment]
Not yet, Thank you!

**Comment by zengxi-hada** [comment]
> Hi @zengxi-hada, did you manage to install dysgu? Come to think of it, you could also try reinstalling pysam. Or if you have conda available, try creating a conda environment...

Not yet, Thank you!

**Comment by kcleal** [comment]
Dysgu has revived an update to 1.6.0. It's possible the error you experience has disappeared.

**Comment by kcleal** [comment]
Closing this for now. Please re-open if you still have the issue
