### ISSUE TITLE
OverflowError: can't convert negative value to size_t

### ISSUE THREAD

**Issue by wenyuhaokikika** [kcleal/dysgu#68]
Thank you for providing dysgu such a good tool~~~

I have 8 samples with a sequencing depth of 45X,  the first 7 samples ran successfully, but the last one encountered an issue. I attempted to re-run BWA mem, but the problem persisted. This sample is from human HET293T cell line's WGS sequencing with a sequencing depth of 45X. The data is sourced from PRJNA565658, with the SRA accession number SRR10129631. I initially used the sratoolkit tool 'prefetch' to download the raw data and then converted it to fastq format using 'fastq-dump'. Finally, I ran BWA mem with the following code.

```
$ dysgu --version
dysgu, version 1.5.0

sample=SRR10129631
bwa mem -t 30 -R "@RG\tID:"$sample"\tSM:"$sample"\tPL:ILLUMINA" /data/wenyuhao/55/CCLE/raw/resources/genome.fasta $sample"_1.fastq" $sample"_2.fastq" | samtools sort -T ./TMP/ -o $sample"_sorted1.bam" -
dysgu run -x -p4 /data/wenyuhao/55/CCLE/raw/resources/genome.fasta TMP $sample"_sorted1.bam" > $sample"_dysgu.vcf"
```
then it raise Exception, that why?
```
$ dysgu run -x -p4 /data/wenyuhao/55/CCLE/raw/resources/genome.fasta TMP $sample"_sorted1.bam" > $sample"_dysgu.vcf"                     
2023-08-25 10:03:03,242 [INFO   ]  [dysgu-run] Version: 1.5.0
2023-08-25 10:03:03,242 [INFO   ]  run -x -p4 --contigs False /data/wenyuhao/55/CCLE/raw/resources/genome.fasta TMP SRR10129631_sorted1.bam
2023-08-25 10:03:03,242 [INFO   ]  Destination: TMP
2023-08-25 10:22:26,198 [INFO   ]  dysgu fetch SRR10129631_sorted1.bam written to TMP/SRR10129631_sorted1.dysgu_reads.bam, n=16505931, time=0:19:22 h:m:s
2023-08-25 10:22:26,198 [INFO   ]  Input file is: TMP/SRR10129631_sorted1.dysgu_reads.bam
2023-08-25 10:22:26,438 [INFO   ]  Sample name: SRR10129631
2023-08-25 10:22:26,438 [INFO   ]  Writing vcf to stdout
2023-08-25 10:22:26,438 [INFO   ]  Running pipeline
2023-08-25 10:22:26,898 [INFO   ]  Calculating insert size. Removed 47 outliers with insert size >= 835.0
2023-08-25 10:22:26,913 [INFO   ]  Inferred read length 151.0, insert median 387, insert stdev 87
2023-08-25 10:22:26,914 [INFO   ]  Max clustering dist 822
2023-08-25 10:22:26,915 [INFO   ]  Minimum support 3
2023-08-25 10:22:26,915 [INFO   ]  Building graph with clustering 822 bp
2023-08-25 10:27:51,487 [INFO   ]  Total input reads 16505931
2023-08-25 10:27:57,417 [INFO   ]  Graph constructed
Traceback (most recent call last):
  File "/home/wenyuhao/anaconda3/envs/dysgu/bin/dysgu", line 11, in <module>
    sys.exit(cli())
  File "/home/wenyuhao/anaconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/wenyuhao/anaconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/wenyuhao/anaconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wenyuhao/anaconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wenyuhao/anaconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/wenyuhao/anaconda3/envs/dysgu/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/wenyuhao/anaconda3/envs/dysgu/lib/python3.10/site-packages/dysgu/main.py", line 256, in run_pipeline
    cluster.cluster_reads(ctx.obj)
  File "dysgu/cluster.pyx", line 1079, in dysgu.cluster.cluster_reads
  File "dysgu/cluster.pyx", line 883, in dysgu.cluster.pipe1
  File "dysgu/graph.pyx", line 1424, in dysgu.graph.proc_component
  File "dysgu/graph.pyx", line 1444, in dysgu.graph.proc_component
  File "dysgu/graph.pyx", line 574, in dysgu.graph.NodeToName.__getitem__
OverflowError: can't convert negative value to size_t
```

**Comment by kcleal** [comment]
Hi @wenyuhaokikika,
Could you upgrade dysgu to v1.6.0? It's possible this error has been fixed in the latest release.

**Comment by wenyuhaokikika** [comment]
Problem solved, thank you very much and Dysgu~~~
