### ISSUE TITLE
Error installing with conda

### ISSUE THREAD

**Issue by jbruxaux** [kcleal/dysgu#90]
Hi!

I have an error when running dysgu test.
I get this message:
```
2024-04-29 14:47:56,143 [INFO   ]  [dysgu-test] Version: 1.6.2
Traceback (most recent call last):
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/bin/dysgu", line 11, in <module>
    sys.exit(cli())
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/dysgu/main.py", line 534, in test_command
    v = run(shlex.split(c), shell=False, capture_output=True, check=True)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dysgu', 'fetch', '-x', '/pfs/stor10/projects/projnb10/snic2019-29-3/wd_test', '/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/dysgu/tests/small.bam']' returned non-zero exit status 1.
```

I have installed dysgu using conda. I have all the packages requested:
```
# packages in environment at /home/j/jbruxaux/miniconda3/envs/dysgu:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cython                    3.0.10          py310hc6cd4ac_0    conda-forge
dysgu                     1.6.2           py310h770aed0_0    bioconda
htslib                    1.20                 h81da01d_0    bioconda
joblib                    1.4.0              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h55db66e_0    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libcurl                   8.7.1                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               hc881cc4_6    conda-forge
libgfortran-ng            13.2.0               h69a702a_6    conda-forge
libgfortran5              13.2.0               h43f5ff8_6    conda-forge
libgomp                   13.2.0               hc881cc4_6    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h95c4c6d_6    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lightgbm                  4.3.0           py310hc6cd4ac_0    conda-forge
ncurses                   6.4.20240210         h59595ed_0    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
numpy                     1.26.4          py310hb13e2d6_0    conda-forge
openssl                   3.2.1                hd590300_1    conda-forge
pandas                    2.2.2           py310hcc13569_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pysam                     0.22.0          py310h41dec4a_1    bioconda
python                    3.10.14         hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-edlib              1.3.9           py310h0dbaff4_6    bioconda
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scikit-learn              1.4.2           py310h1fdf081_0    conda-forge
scipy                     1.13.0          py310hb13e2d6_0    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.4.0              pyhc1e730c_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

I use conda 24.3.0 in case it matters.

Any suggestion?

Thanks in advance!

**Comment by jbruxaux** [comment]
Thanks for your quick reply!
Here is the log:
```
2024-04-29 16:48:08,211 [INFO   ]  [dysgu-fetch] Version: 1.6.2
Traceback (most recent call last):
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/bin/dysgu", line 11, in <module>
    sys.exit(cli())
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/dysgu/main.py", line 303, in get_reads
    return sv2bam.process(ctx.obj)
  File "dysgu/sv2bam.pyx", line 165, in dysgu.sv2bam.process
  File "dysgu/sv2bam.pyx", line 166, in dysgu.sv2bam.process
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/pkg_resources/__init__.py", line 937, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/pkg_resources/__init__.py", line 798, in resolve
    dist = self._resolve_dist(
  File "/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pysam 0.22.0 (/pfs/stor10/users/home/j/jbruxaux/miniconda3/envs/dysgu/lib/python3.10/site-packages), Requirement.parse('pysam==0.21.0'), {'dysgu'})
```
Should I try to use pysam v.0.21.0 instead of 0.22.0 that was in the requirement file?

**Comment by kcleal** [comment]
Ah interesting. Im not sure where the requirement for 0.21 is from. The conda recipe if for pysam >= 0.19 and the master branch is pysam == 0.22. Are you able to using pip install?

**Comment by jbruxaux** [comment]
It works with pip install:
```
2024-04-29 17:04:24,989 [INFO   ]  [dysgu-test] Version: 1.6.3
PASS: dysgu fetch -x  /pfs/stor10/projects/projnb10/snic2019-29-3/wd_test /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/small.bam

PASS: dysgu run -x --drop-gaps False -o /pfs/stor10/projects/projnb10/snic2019-29-3/test.dysgu1.6.3.vcf /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/ref.fa /pfs/stor10/projects/projnb10/snic2019-29-3/wd_test /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/small.bam

PASS: dysgu run -x --drop-gaps False --regions /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/targets.bed -o /pfs/stor10/projects/projnb10/snic2019-29-3/test_regions.dysgu1.6.3.vcf /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/ref.fa /pfs/stor10/projects/projnb10/snic2019-29-3/wd_test2 /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/small.bam

PASS: dysgu run -x --drop-gaps False --procs 2 --regions /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/targets.bed -o /pfs/stor10/projects/projnb10/snic2019-29-3/test_regions.dysgu1.6.3.vcf /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/ref.fa /pfs/stor10/projects/projnb10/snic2019-29-3/wd_test2 /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/small.bam

PASS: dysgu run -x --drop-gaps False --mode pacbio -o /pfs/stor10/projects/projnb10/snic2019-29-3/test2.dysgu1.6.3.vcf /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/ref.fa /pfs/stor10/projects/projnb10/snic2019-29-3/wd_test /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/small.bam

PASS: dysgu call -x --drop-gaps False -o /pfs/stor10/projects/projnb10/snic2019-29-3/test2.dysgu1.6.3.vcf /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/ref.fa /pfs/stor10/projects/projnb10/snic2019-29-3/wd_test /home/j/jbruxaux/.local/lib/python3.11/site-packages/dysgu/tests/small.bam

PASS: dysgu merge /pfs/stor10/projects/projnb10/snic2019-29-3/test.dysgu1.6.3.vcf /pfs/stor10/projects/projnb10/snic2019-29-3/test2.dysgu1.6.3.vcf -o /pfs/stor10/projects/projnb10/snic2019-29-3/test.merge.dysgu1.6.3.vcf

2024-04-29 17:05:07,258 [INFO   ]  Run test complete
```
Thanks!
Let me know if you want to explore more the conda issue in the meantime.

**Comment by kcleal** [comment]
I think the has now been resolved, please re-open of not.
